#!/usr/bin/env bash
#
# @(#) request-apache-certs
#
# Copyright © 2022 Revolution Robotics, Inc.
#
: ${CERTBOT_CMD:='/usr/bin/certbot'}
: ${OPENSSL_CMD:='/usr/bin/openssl'}
: ${READLINK_CMD:='/usr/bin/readlink'}

request-tls-certificates ()
{
    local email_address=$1
    local fqdn=$2

    $CERTBOT_CMD run \
            --non-interactive \
            --agree-tos \
            --email "$email_address" \
            --apache \
            --keep-until-expiring \
            --preferred-challenges http \
            -d "$fqdn"
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare script=$($READLINK_CMD -e "$0")
    declare script_name=${script##*/}
    declare script_dir=${script%/*}

    declare email_address=$1
    declare fqdn=$2

    if (( UID != 0 )); then
        echo "${script_name}: This script must be run as user \`root'." >&2
        exit 1
    fi

    if ! "${script_dir}/is-valid-email" "$email_address" \
            || ! "${script_dir}/is-valid-domain-name" "$fqdn"; then
        echo "Usage: ${script_name} email-address domain-name" >&2
        exit 1
    fi

    request-tls-certificates "$email_address" "$fqdn"

    if test ! -f /etc/letsencrypt/dhparams.pem; then
        $OPENSSL_CMD dhparam -out /etc/letsencrypt/dhparams.pem 4096
    fi
fi
