dev_db_name: ENC[AES256_GCM,data:M4EbNrpDj5uDxY3/x2leLWALaTqvBx4=,iv:VTyGS8YYs4FL5wqeA98ucDmugMyRTxEqQsbpHEo9Tog=,tag:bSNiD5Ah5ESztRCg55Gu9Q==,type:str]
dev_db_user: ENC[AES256_GCM,data:m1I4zg==,iv:jbiRZ3ezPeso0a1Gz49I66SViFpbX00cao6TwqPlYSY=,tag:Y94ssQtJbYkv1+U7KQO9qA==,type:str]
dev_db_pass: ENC[AES256_GCM,data:GAmwpwxXUEzZKtde7EUuhXLlBOzH2Q==,iv:OwI2bgjB6xJJxnGj/dLrx1Me0Nb7qgQ61ttWRaImpFg=,tag:gjrucUm+QJ1hsRWmCYILrw==,type:str]
dev_db_host: ENC[AES256_GCM,data:pJyQn1mgz5+R,iv:JjgpNyPv4Zh1pJvpxlJb1SQ//U/1fQniAe/cKBWBO2M=,tag:PJlKb/RGDcLW15MlTNgntg==,type:str]
dev_db_port: ENC[AES256_GCM,data:86JYbA==,iv:2HAcmqBLfEuR1kJ4Qc9UhhMU/MPY5mvb4V9pq3NEd2I=,tag:fjIyRGxEEYLT8nDX8vYAhQ==,type:int]
test_db_name: ENC[AES256_GCM,data:utqiqSlDFmqONhnad5zU/A==,iv:l4ffzAy5vEVr5LQBt0CVvzA5C6tw7HKa6F0FkM1jNEs=,tag:ZaO+1Ez/HoRyQEW3P/wtGw==,type:str]
test_db_user: ENC[AES256_GCM,data:Ve5sHw==,iv:5M8vhTvLNk0MM4iUSxWGNzmEklJ48irVawqTu2bjllk=,tag:iUsjVyYhDtZlHeO4hKAJfg==,type:str]
test_db_pass: ENC[AES256_GCM,data:UpxQPskfAC3AdYKhLegHeWalAki7ag==,iv:Do+CHfPX6q85ZUK1hFrzO3PKyrrjjj0iDRgj7C+HAsE=,tag:d9qs056HrYGenJzjwlsrgQ==,type:str]
test_db_host: ENC[AES256_GCM,data:BfPKlCtKK+kA,iv:YsKgG/vE8lxOKMTd0qpYOv+HLvh9u7fQknB6jSJinlo=,tag:RFE3vbOEjdndUzj4VijWpQ==,type:str]
test_db_port: ENC[AES256_GCM,data:wX+xfA==,iv:Ll4JAEiglK1QqwxTTjH/gSe+99bcuDq1DWGs7GFFhk4=,tag:0Xx8vzr5fOuQbk7TJEj39g==,type:int]
prod_db_name: ENC[AES256_GCM,data:8o4rigxx6vE0Tfw=,iv:KF68vUdQO3R3aTMaFzhSbuZQS3ASLosm2gTEtpHRj/k=,tag:abdywCkZxNfy7MMxQTy44A==,type:str]
prod_db_user: ENC[AES256_GCM,data:7ZnoshfhotrtuKc=,iv:5m1lMJlHjJjXIw6PKDSg4D5HNL2KFiTQWmpsl3WFit0=,tag:H/If7qJwt5GBSoTgFW2vxw==,type:str]
prod_db_pass: ENC[AES256_GCM,data:y/CtQKwPg1N/Ys2R71k2H3bFojlX2w==,iv:LWIwb/cpm4umNKgimb6VJLYh2BqcTitZMHOvPb0X2tk=,tag:LOZIiHxo8+rXuHnFOHcnqg==,type:str]
prod_db_host: ENC[AES256_GCM,data:FGVRcSFoQvTx,iv:lB75ONRfvgG6z28KvvffNDhKkNCcKRLmUsrXn46T5io=,tag:ynOxTsIdgGv3gQRhEdg0IA==,type:str]
prod_db_port: ENC[AES256_GCM,data:KYdIHQ==,iv:mPpRBiokqzgqSP+N3Q/ZwKS1387qgP/VX/EVh7E5pj8=,tag:VkQdQ8PzTNTj1eJx2a9O0g==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13jd25wcjch6sqfk4s87j4yuaa5j38qsujn9yqgaa9wlxvzqjx3ps7ze428
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Mndmd0lJRTdQZGthOEdW
            VnE5VXdzZmFDSnlrZ0hmZGIwVHdURmtNeXlzCmlNUWhjSUF5VlJjM2pOMmZQZGZw
            a1Y3bnFYck1LUWdKZlY1QjRKUG9lNzAKLS0tIHdWU1BJV1FzVWNnS2o1NUh0MFZQ
            NWtVanNjR1YxY1l4SzgwWFhUcE5QQ0kKttSripnCp0MHkbqrUoy10XUHkru/6VAu
            tz3jYbEWD1SJWz4ZgmERT6yy3gk3OE6VBiZ+TZ5gOVgHIQEN0gUxOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uqh0uaa38dqttjaf9d9nmgqfedmk4tshe3hlr45sp638aqe60qsqtw7vld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRmtDK3NQTnA2aDlHd2dZ
            aDNWYW5Pa1VvdDlORkx2MnFLYTlOWHE4UVhzCmtqbVRpaDl3dWlRaktJdmUzK1Jw
            Y2t2VFVpU1VKWnNpY0ZBaWxEcVhXR1kKLS0tIFhYRGVQNk5YYzlHR05qV3JQNlBo
            Zk1jRjU4eXVETVdZV1haTnNpYlJyNG8KHR0fGzumFj8YDehTBYbazWyd1iNaxkXt
            5DqlCnaNsc7OCaJjRG1H4VmZnajJ0JcpEDbkXs6enIhA//v5DpoNXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-02T11:02:43Z"
    mac: ENC[AES256_GCM,data:HygMUg9eiYZdDYhsX8K6PQyf3JQsE087wjxLCGOqIzvlJN2E9LdesgXryMmcTP08lembbHbEVH3Yxj3YTXW+16lVc/Y4+91ETQF/L/Q26hCy/aC7LNB9JK/BtI3PPCqxsEiBr2T3YhNL5DxtUcPyID5whxfszovC17jGhH/WhSM=,iv:/uyPuJHAXq7RPBzHK9E7IpGvSgeRCQXl6LHX/z5FQYk=,tag:oDpUqxb6lVu5/RxqyJWeIA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
